In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) - skipping
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
a2=np.array(((1,2,3),(4,5,6)))

In [4]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(a2)

numpy.ndarray

In [6]:
a2.ndim

2

In [7]:
a3=np.zeros((4,4))

In [8]:
a3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a4=np.ones((3,4))

In [10]:
a4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
a5=np.random.random((3,9))

In [12]:
a5

array([[0.0538738 , 0.23165116, 0.4997054 , 0.29213835, 0.64922224,
        0.22417657, 0.22047405, 0.64310428, 0.10818975],
       [0.72406218, 0.10835026, 0.26163441, 0.34142369, 0.44830223,
        0.36670127, 0.52447082, 0.18388506, 0.79961134],
       [0.57871161, 0.61613178, 0.43514711, 0.59544573, 0.50898217,
        0.32679115, 0.94830963, 0.38394138, 0.3538194 ]])

In [13]:
a6=np.arange(10,0,-1)
a6

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### NOTE - if floating value is given it will convert into complex value .if complex value is given it will convert into integer too

In [14]:
l1=np.linspace(1,10,retstep=True,endpoint=False,dtype='int')

In [15]:
l1

(array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
        4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8,
        8, 9, 9, 9, 9, 9]),
 0.18)

In [16]:
l2=a5.reshape((9,3))  #it shape an array without changing data of array

In [17]:
l2

array([[0.0538738 , 0.23165116, 0.4997054 ],
       [0.29213835, 0.64922224, 0.22417657],
       [0.22047405, 0.64310428, 0.10818975],
       [0.72406218, 0.10835026, 0.26163441],
       [0.34142369, 0.44830223, 0.36670127],
       [0.52447082, 0.18388506, 0.79961134],
       [0.57871161, 0.61613178, 0.43514711],
       [0.59544573, 0.50898217, 0.32679115],
       [0.94830963, 0.38394138, 0.3538194 ]])

In [18]:
l3=l2.flatten()

In [19]:
l3

array([0.0538738 , 0.23165116, 0.4997054 , 0.29213835, 0.64922224,
       0.22417657, 0.22047405, 0.64310428, 0.10818975, 0.72406218,
       0.10835026, 0.26163441, 0.34142369, 0.44830223, 0.36670127,
       0.52447082, 0.18388506, 0.79961134, 0.57871161, 0.61613178,
       0.43514711, 0.59544573, 0.50898217, 0.32679115, 0.94830963,
       0.38394138, 0.3538194 ])

In [20]:
l3.ndim

1

In [21]:
l4=np.array([[10,2+5j],[11,3+5j]])

In [22]:
l4

array([[10.+0.j,  2.+5.j],
       [11.+0.j,  3.+5.j]])

In [23]:
l4.dtype

dtype('complex128')

In [24]:
l5=np.array([[11,12.3],[12,8.9]])

In [25]:
l5

array([[11. , 12.3],
       [12. ,  8.9]])

In [26]:
l5.dtype

dtype('float64')

In [27]:
len(l5)

2

In [28]:
len(l3)

27

#### size - shows the no.of elements in the array

In [29]:
a5

array([[0.0538738 , 0.23165116, 0.4997054 , 0.29213835, 0.64922224,
        0.22417657, 0.22047405, 0.64310428, 0.10818975],
       [0.72406218, 0.10835026, 0.26163441, 0.34142369, 0.44830223,
        0.36670127, 0.52447082, 0.18388506, 0.79961134],
       [0.57871161, 0.61613178, 0.43514711, 0.59544573, 0.50898217,
        0.32679115, 0.94830963, 0.38394138, 0.3538194 ]])

In [30]:
l5.size

4

In [31]:
a5.size

27

In [32]:
a5.itemsize

8

In [33]:
l4.itemsize

16

In [34]:
l4.shape

(2, 2)

In [35]:
a5.shape

(3, 9)

In [36]:
type(l4)

numpy.ndarray

In [37]:
a5.T   #T stands for transpose property

array([[0.0538738 , 0.72406218, 0.57871161],
       [0.23165116, 0.10835026, 0.61613178],
       [0.4997054 , 0.26163441, 0.43514711],
       [0.29213835, 0.34142369, 0.59544573],
       [0.64922224, 0.44830223, 0.50898217],
       [0.22417657, 0.36670127, 0.32679115],
       [0.22047405, 0.52447082, 0.94830963],
       [0.64310428, 0.18388506, 0.38394138],
       [0.10818975, 0.79961134, 0.3538194 ]])

In [38]:
a5.transpose()   #tranpsose is a function 

array([[0.0538738 , 0.72406218, 0.57871161],
       [0.23165116, 0.10835026, 0.61613178],
       [0.4997054 , 0.26163441, 0.43514711],
       [0.29213835, 0.34142369, 0.59544573],
       [0.64922224, 0.44830223, 0.50898217],
       [0.22417657, 0.36670127, 0.32679115],
       [0.22047405, 0.52447082, 0.94830963],
       [0.64310428, 0.18388506, 0.38394138],
       [0.10818975, 0.79961134, 0.3538194 ]])

## indexing and slicing

In [39]:
a11=np.arange(21,31)

In [40]:
a11

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
a11[-1]

30

In [42]:
a12=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
a12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a12[1][2]

6

In [45]:
a12[2][2]

9

## Slicing

In [46]:
a11

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [47]:
a11[4:8:1]

array([25, 26, 27, 28])

In [48]:
a12

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### array[row,col]

In [49]:
a12[0,0:3]

array([1, 2, 3])

In [50]:
a12[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [51]:
a12[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [52]:
a12[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [53]:
a12[2:3,2:3][0][0]

9

In [54]:
a12[2,0:2]

array([7, 8])

# Arithmetic operator

In [55]:
b=np.array([[1,2,3],[4,5,6]])

In [56]:
c=np.array([[7,8,9],[10,11,12]])

In [57]:
np.add(b,c)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [58]:
np.subtract(c,b)

array([[6, 6, 6],
       [6, 6, 6]])

In [59]:
np.multiply(c,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [60]:
np.divide(b,c)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [61]:
np.mod(c,b)

array([[0, 0, 0],
       [2, 1, 0]])