# BROADCASTING - it describes how numpy treats arrays with different shapes during arithmetic operations.

In [5]:
import numpy as np

In [6]:
x=list(range(1,11))

In [7]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
x*2  #multiplication

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
x1=np.arange(1,11)

In [10]:
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
x1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
x1*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
x1-3

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [14]:
x1+4

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
x1/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# statistical function

In [16]:
a=np.array([[1,2,3],[4,5,6]])

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(a)

1

In [19]:
np.max(a)

6

In [20]:
np.min(a,axis=1)   #axis =1 shows column wise

array([1, 4])

In [21]:
np.min(a,axis=0)   #axis=0 shows row wise

array([1, 2, 3])

In [22]:
np.average(a)

3.5

In [23]:
np.mean(a)

3.5

In [24]:
np.median(a)

3.5

In [27]:
np.sum(a)  #addition

21

In [30]:
np.var(a)   #variance

2.9166666666666665

In [31]:
np.std(a)     #standard deviation

1.707825127659933

In [32]:
np.sum(a)

21

In [33]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [36]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [37]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

# concatination

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b=np.array([[7,8,9],[10,11,12]])

In [40]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [41]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# insert

In [43]:
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.insert(x1,4,55)    #array , value in the array(index no), any value you have to insert 

array([ 1,  2,  3,  4, 55,  5,  6,  7,  8,  9, 10])

# delete

In [48]:
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.delete(x1,-3)

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

# Masking (vectorization)

#### if i want to apply a condition and based on condition i want output

In [50]:
z=np.arange(1,16)

In [51]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
z>8

array([False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True])

In [53]:
mask=z>8
z[mask]

array([ 9, 10, 11, 12, 13, 14, 15])

In [57]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
z[z%2==0]          #finding even nos

array([ 2,  4,  6,  8, 10, 12, 14])

In [59]:
z[z%2!=0]           #finding odd nos

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# Selection in array

In [60]:
names=np.array(['sejal','raj','tej','raj','tej','deep'])

In [61]:
names

array(['sejal', 'raj', 'tej', 'raj', 'tej', 'deep'], dtype='<U5')

#### find names except raj

In [62]:
names[names!='raj']

array(['sejal', 'tej', 'tej', 'deep'], dtype='<U5')

#### find names except raj and tej

In [63]:
names[(names!='raj') & (names!='tej')]

array(['sejal', 'deep'], dtype='<U5')

In [64]:
A=np.array([2,5,7,8,19,17,15,16,55,7,9])

In [65]:
A

array([ 2,  5,  7,  8, 19, 17, 15, 16, 55,  7,  9])

#### find nos divisible 3 & 7

In [70]:
A[(A%3==0) | (A%7==0)]

array([ 7, 15,  7,  9])

#### find nos which are not divisible by 3 and 7

In [71]:
A[(A%3!=0) & (A%7!=0)]

array([ 2,  5,  8, 19, 17, 16, 55])